//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.0
//     from Assets/Prefabs/Minigame1/MiniGame1_InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Prefabs/Minigame1/MiniGame1_InputActions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @MiniGame1_InputActions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @MiniGame1_InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MiniGame1_InputActions"",
    ""maps"": [
        {
            ""name"": ""PlayerRunner"",
            ""id"": ""844d886c-fad4-4657-8b72-ec9137345b52"",
            ""actions"": [
                {
                    ""name"": ""MoveToLane1"",
                    ""type"": ""Button"",
                    ""id"": ""0306cb78-912e-40a2-9956-2faf26fa3bfe"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveToLane2"",
                    ""type"": ""Button"",
                    ""id"": ""c7bb22a8-843f-449e-8cb3-b183ad32b392"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveToLane3"",
                    ""type"": ""Button"",
                    ""id"": ""18ce9314-d195-4c31-836a-7566a2da3e48"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveToLane4"",
                    ""type"": ""Button"",
                    ""id"": ""e4cad7b5-c3d2-451d-86af-626585f4abd6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5d3ddf54-5117-4897-83d9-f3a5b74abd1b"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""MoveToLane1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2a98425e-846c-4c0c-a491-fb9b3261346b"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""MoveToLane1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f9ad56fe-bcb3-46e4-b818-93cd8f68a7fc"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""MoveToLane2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f3caeb46-33c2-480b-ba21-739037dbaaa7"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""MoveToLane2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""08182bf0-0e14-4683-ad7e-62c72e26e442"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""MoveToLane3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6cb92bfa-1f6f-48b9-bfe2-0a07f8c3c58c"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""MoveToLane3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""769f842c-ce61-4f18-b52d-08488ecc8c4f"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""MoveToLane4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d8dfef46-10eb-449a-be91-7d00c82a686c"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""MoveToLane4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerRunner1"",
            ""id"": ""2d72768d-cb6e-4fb0-a9bb-5bb3272d487d"",
            ""actions"": [
                {
                    ""name"": ""MoveToLane1"",
                    ""type"": ""Button"",
                    ""id"": ""e13c56fa-a48a-4f51-8e21-f43de0c5a2e3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveToLane2"",
                    ""type"": ""Button"",
                    ""id"": ""fe1aacb9-5d80-43f0-ab8a-a1a58a42b99b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveToLane3"",
                    ""type"": ""Button"",
                    ""id"": ""6e291f37-89e1-4a3c-821a-149934d07f3d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveToLane4"",
                    ""type"": ""Button"",
                    ""id"": ""ef32bd2b-2976-409b-8317-0332bc2aca5f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""6c03dae4-4a41-4778-9efe-73156a34341c"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""MoveToLane1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1a4cdb23-4411-4b45-85b9-7cdda033a4eb"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""MoveToLane1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""34e7e74e-f474-4d89-b4e0-65dfab4f7a39"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""MoveToLane2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""41acab2b-7c2f-4e64-9fac-d43a8e14b40f"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""MoveToLane2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""055c6521-c3f2-4e68-b8c0-a2d6a6f37970"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""MoveToLane3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0ec9d785-af02-4c09-9051-7146c79fb46f"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""MoveToLane3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0cb7b228-6bf5-46c2-a44d-7a04eee83e60"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""MoveToLane4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""abb5f1ea-9c83-4d8f-b3e9-c2c9f584ce66"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""MoveToLane4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerRunner2"",
            ""id"": ""51e71e13-cf8e-4124-bc59-9a36e8dd010c"",
            ""actions"": [
                {
                    ""name"": ""MoveToLane1"",
                    ""type"": ""Button"",
                    ""id"": ""04e47ad5-c70e-4756-b047-40f8eddadaf9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveToLane2"",
                    ""type"": ""Button"",
                    ""id"": ""f4f74a80-2c94-498e-aff6-9e90e85b1ac7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveToLane3"",
                    ""type"": ""Button"",
                    ""id"": ""88618e20-6748-4e86-9156-a634bdccbe47"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveToLane4"",
                    ""type"": ""Button"",
                    ""id"": ""352134df-22b6-4f87-9d9c-7188f3da0028"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""66400540-c0d1-4313-9a26-2e80bd1e44e8"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""MoveToLane1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""191a98e6-5dcf-43ca-a91e-e3f0d7fba774"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""MoveToLane1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""713eadca-1027-47e8-b1bf-f9419b000a5c"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""MoveToLane2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5ab10393-2fd9-4590-a334-6152485f0153"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""MoveToLane2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86508164-efde-4db4-9b04-1d59745b5b36"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""MoveToLane3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e2bade01-552b-4a03-867f-a26a8c0f26cd"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""MoveToLane3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a08c5f4-e7a9-4b67-981b-daf777fdba88"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""MoveToLane4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""230bfb16-9306-47db-a080-7b31cf820a75"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""MoveToLane4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerRunner3"",
            ""id"": ""20311349-52be-4da1-86d4-a568aebf925d"",
            ""actions"": [
                {
                    ""name"": ""MoveToLane1"",
                    ""type"": ""Button"",
                    ""id"": ""15e1189b-bb8b-4d95-b55d-5274962026dc"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveToLane2"",
                    ""type"": ""Button"",
                    ""id"": ""805c7148-11f7-418a-bde9-cde455e3451b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveToLane3"",
                    ""type"": ""Button"",
                    ""id"": ""83bf3e14-7a49-42d7-ad31-cd36dddf387e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveToLane4"",
                    ""type"": ""Button"",
                    ""id"": ""bce27c0d-b2c3-4ef5-8646-3d0ad266594e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7404f852-5cd4-4208-806e-6feed89a37d2"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""MoveToLane1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""83015ed4-3a3a-4e8b-bfda-acac8c38ef98"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""MoveToLane1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fe1348a8-6b24-4720-8725-b835dfd24cbf"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""MoveToLane2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""65bab4a0-7305-4c12-9508-0fea610d4125"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""MoveToLane2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7e91d977-0d7d-464d-9f10-27032fb964fc"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""MoveToLane3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""91eb5cf7-07fa-4715-8355-b6e3b0c0ad6c"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""MoveToLane3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e7d4d3d0-96b6-4a28-8fe2-152fb299eaf8"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""MoveToLane4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""96f80383-b676-4089-8184-c34cd7d4a556"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""MoveToLane4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // PlayerRunner
        m_PlayerRunner = asset.FindActionMap("PlayerRunner", throwIfNotFound: true);
        m_PlayerRunner_MoveToLane1 = m_PlayerRunner.FindAction("MoveToLane1", throwIfNotFound: true);
        m_PlayerRunner_MoveToLane2 = m_PlayerRunner.FindAction("MoveToLane2", throwIfNotFound: true);
        m_PlayerRunner_MoveToLane3 = m_PlayerRunner.FindAction("MoveToLane3", throwIfNotFound: true);
        m_PlayerRunner_MoveToLane4 = m_PlayerRunner.FindAction("MoveToLane4", throwIfNotFound: true);
        // PlayerRunner1
        m_PlayerRunner1 = asset.FindActionMap("PlayerRunner1", throwIfNotFound: true);
        m_PlayerRunner1_MoveToLane1 = m_PlayerRunner1.FindAction("MoveToLane1", throwIfNotFound: true);
        m_PlayerRunner1_MoveToLane2 = m_PlayerRunner1.FindAction("MoveToLane2", throwIfNotFound: true);
        m_PlayerRunner1_MoveToLane3 = m_PlayerRunner1.FindAction("MoveToLane3", throwIfNotFound: true);
        m_PlayerRunner1_MoveToLane4 = m_PlayerRunner1.FindAction("MoveToLane4", throwIfNotFound: true);
        // PlayerRunner2
        m_PlayerRunner2 = asset.FindActionMap("PlayerRunner2", throwIfNotFound: true);
        m_PlayerRunner2_MoveToLane1 = m_PlayerRunner2.FindAction("MoveToLane1", throwIfNotFound: true);
        m_PlayerRunner2_MoveToLane2 = m_PlayerRunner2.FindAction("MoveToLane2", throwIfNotFound: true);
        m_PlayerRunner2_MoveToLane3 = m_PlayerRunner2.FindAction("MoveToLane3", throwIfNotFound: true);
        m_PlayerRunner2_MoveToLane4 = m_PlayerRunner2.FindAction("MoveToLane4", throwIfNotFound: true);
        // PlayerRunner3
        m_PlayerRunner3 = asset.FindActionMap("PlayerRunner3", throwIfNotFound: true);
        m_PlayerRunner3_MoveToLane1 = m_PlayerRunner3.FindAction("MoveToLane1", throwIfNotFound: true);
        m_PlayerRunner3_MoveToLane2 = m_PlayerRunner3.FindAction("MoveToLane2", throwIfNotFound: true);
        m_PlayerRunner3_MoveToLane3 = m_PlayerRunner3.FindAction("MoveToLane3", throwIfNotFound: true);
        m_PlayerRunner3_MoveToLane4 = m_PlayerRunner3.FindAction("MoveToLane4", throwIfNotFound: true);
    }

    ~@MiniGame1_InputActions()
    {
        UnityEngine.Debug.Assert(!m_PlayerRunner.enabled, "This will cause a leak and performance issues, MiniGame1_InputActions.PlayerRunner.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_PlayerRunner1.enabled, "This will cause a leak and performance issues, MiniGame1_InputActions.PlayerRunner1.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_PlayerRunner2.enabled, "This will cause a leak and performance issues, MiniGame1_InputActions.PlayerRunner2.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_PlayerRunner3.enabled, "This will cause a leak and performance issues, MiniGame1_InputActions.PlayerRunner3.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerRunner
    private readonly InputActionMap m_PlayerRunner;
    private List<IPlayerRunnerActions> m_PlayerRunnerActionsCallbackInterfaces = new List<IPlayerRunnerActions>();
    private readonly InputAction m_PlayerRunner_MoveToLane1;
    private readonly InputAction m_PlayerRunner_MoveToLane2;
    private readonly InputAction m_PlayerRunner_MoveToLane3;
    private readonly InputAction m_PlayerRunner_MoveToLane4;
    /// <summary>
    /// Provides access to input actions defined in input action map "PlayerRunner".
    /// </summary>
    public struct PlayerRunnerActions
    {
        private @MiniGame1_InputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PlayerRunnerActions(@MiniGame1_InputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "PlayerRunner/MoveToLane1".
        /// </summary>
        public InputAction @MoveToLane1 => m_Wrapper.m_PlayerRunner_MoveToLane1;
        /// <summary>
        /// Provides access to the underlying input action "PlayerRunner/MoveToLane2".
        /// </summary>
        public InputAction @MoveToLane2 => m_Wrapper.m_PlayerRunner_MoveToLane2;
        /// <summary>
        /// Provides access to the underlying input action "PlayerRunner/MoveToLane3".
        /// </summary>
        public InputAction @MoveToLane3 => m_Wrapper.m_PlayerRunner_MoveToLane3;
        /// <summary>
        /// Provides access to the underlying input action "PlayerRunner/MoveToLane4".
        /// </summary>
        public InputAction @MoveToLane4 => m_Wrapper.m_PlayerRunner_MoveToLane4;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_PlayerRunner; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PlayerRunnerActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PlayerRunnerActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PlayerRunnerActions" />
        public void AddCallbacks(IPlayerRunnerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerRunnerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerRunnerActionsCallbackInterfaces.Add(instance);
            @MoveToLane1.started += instance.OnMoveToLane1;
            @MoveToLane1.performed += instance.OnMoveToLane1;
            @MoveToLane1.canceled += instance.OnMoveToLane1;
            @MoveToLane2.started += instance.OnMoveToLane2;
            @MoveToLane2.performed += instance.OnMoveToLane2;
            @MoveToLane2.canceled += instance.OnMoveToLane2;
            @MoveToLane3.started += instance.OnMoveToLane3;
            @MoveToLane3.performed += instance.OnMoveToLane3;
            @MoveToLane3.canceled += instance.OnMoveToLane3;
            @MoveToLane4.started += instance.OnMoveToLane4;
            @MoveToLane4.performed += instance.OnMoveToLane4;
            @MoveToLane4.canceled += instance.OnMoveToLane4;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PlayerRunnerActions" />
        private void UnregisterCallbacks(IPlayerRunnerActions instance)
        {
            @MoveToLane1.started -= instance.OnMoveToLane1;
            @MoveToLane1.performed -= instance.OnMoveToLane1;
            @MoveToLane1.canceled -= instance.OnMoveToLane1;
            @MoveToLane2.started -= instance.OnMoveToLane2;
            @MoveToLane2.performed -= instance.OnMoveToLane2;
            @MoveToLane2.canceled -= instance.OnMoveToLane2;
            @MoveToLane3.started -= instance.OnMoveToLane3;
            @MoveToLane3.performed -= instance.OnMoveToLane3;
            @MoveToLane3.canceled -= instance.OnMoveToLane3;
            @MoveToLane4.started -= instance.OnMoveToLane4;
            @MoveToLane4.performed -= instance.OnMoveToLane4;
            @MoveToLane4.canceled -= instance.OnMoveToLane4;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PlayerRunnerActions.UnregisterCallbacks(IPlayerRunnerActions)" />.
        /// </summary>
        /// <seealso cref="PlayerRunnerActions.UnregisterCallbacks(IPlayerRunnerActions)" />
        public void RemoveCallbacks(IPlayerRunnerActions instance)
        {
            if (m_Wrapper.m_PlayerRunnerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PlayerRunnerActions.AddCallbacks(IPlayerRunnerActions)" />
        /// <seealso cref="PlayerRunnerActions.RemoveCallbacks(IPlayerRunnerActions)" />
        /// <seealso cref="PlayerRunnerActions.UnregisterCallbacks(IPlayerRunnerActions)" />
        public void SetCallbacks(IPlayerRunnerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerRunnerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerRunnerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PlayerRunnerActions" /> instance referencing this action map.
    /// </summary>
    public PlayerRunnerActions @PlayerRunner => new PlayerRunnerActions(this);

    // PlayerRunner1
    private readonly InputActionMap m_PlayerRunner1;
    private List<IPlayerRunner1Actions> m_PlayerRunner1ActionsCallbackInterfaces = new List<IPlayerRunner1Actions>();
    private readonly InputAction m_PlayerRunner1_MoveToLane1;
    private readonly InputAction m_PlayerRunner1_MoveToLane2;
    private readonly InputAction m_PlayerRunner1_MoveToLane3;
    private readonly InputAction m_PlayerRunner1_MoveToLane4;
    /// <summary>
    /// Provides access to input actions defined in input action map "PlayerRunner1".
    /// </summary>
    public struct PlayerRunner1Actions
    {
        private @MiniGame1_InputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PlayerRunner1Actions(@MiniGame1_InputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "PlayerRunner1/MoveToLane1".
        /// </summary>
        public InputAction @MoveToLane1 => m_Wrapper.m_PlayerRunner1_MoveToLane1;
        /// <summary>
        /// Provides access to the underlying input action "PlayerRunner1/MoveToLane2".
        /// </summary>
        public InputAction @MoveToLane2 => m_Wrapper.m_PlayerRunner1_MoveToLane2;
        /// <summary>
        /// Provides access to the underlying input action "PlayerRunner1/MoveToLane3".
        /// </summary>
        public InputAction @MoveToLane3 => m_Wrapper.m_PlayerRunner1_MoveToLane3;
        /// <summary>
        /// Provides access to the underlying input action "PlayerRunner1/MoveToLane4".
        /// </summary>
        public InputAction @MoveToLane4 => m_Wrapper.m_PlayerRunner1_MoveToLane4;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_PlayerRunner1; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PlayerRunner1Actions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PlayerRunner1Actions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PlayerRunner1Actions" />
        public void AddCallbacks(IPlayerRunner1Actions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerRunner1ActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerRunner1ActionsCallbackInterfaces.Add(instance);
            @MoveToLane1.started += instance.OnMoveToLane1;
            @MoveToLane1.performed += instance.OnMoveToLane1;
            @MoveToLane1.canceled += instance.OnMoveToLane1;
            @MoveToLane2.started += instance.OnMoveToLane2;
            @MoveToLane2.performed += instance.OnMoveToLane2;
            @MoveToLane2.canceled += instance.OnMoveToLane2;
            @MoveToLane3.started += instance.OnMoveToLane3;
            @MoveToLane3.performed += instance.OnMoveToLane3;
            @MoveToLane3.canceled += instance.OnMoveToLane3;
            @MoveToLane4.started += instance.OnMoveToLane4;
            @MoveToLane4.performed += instance.OnMoveToLane4;
            @MoveToLane4.canceled += instance.OnMoveToLane4;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PlayerRunner1Actions" />
        private void UnregisterCallbacks(IPlayerRunner1Actions instance)
        {
            @MoveToLane1.started -= instance.OnMoveToLane1;
            @MoveToLane1.performed -= instance.OnMoveToLane1;
            @MoveToLane1.canceled -= instance.OnMoveToLane1;
            @MoveToLane2.started -= instance.OnMoveToLane2;
            @MoveToLane2.performed -= instance.OnMoveToLane2;
            @MoveToLane2.canceled -= instance.OnMoveToLane2;
            @MoveToLane3.started -= instance.OnMoveToLane3;
            @MoveToLane3.performed -= instance.OnMoveToLane3;
            @MoveToLane3.canceled -= instance.OnMoveToLane3;
            @MoveToLane4.started -= instance.OnMoveToLane4;
            @MoveToLane4.performed -= instance.OnMoveToLane4;
            @MoveToLane4.canceled -= instance.OnMoveToLane4;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PlayerRunner1Actions.UnregisterCallbacks(IPlayerRunner1Actions)" />.
        /// </summary>
        /// <seealso cref="PlayerRunner1Actions.UnregisterCallbacks(IPlayerRunner1Actions)" />
        public void RemoveCallbacks(IPlayerRunner1Actions instance)
        {
            if (m_Wrapper.m_PlayerRunner1ActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PlayerRunner1Actions.AddCallbacks(IPlayerRunner1Actions)" />
        /// <seealso cref="PlayerRunner1Actions.RemoveCallbacks(IPlayerRunner1Actions)" />
        /// <seealso cref="PlayerRunner1Actions.UnregisterCallbacks(IPlayerRunner1Actions)" />
        public void SetCallbacks(IPlayerRunner1Actions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerRunner1ActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerRunner1ActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PlayerRunner1Actions" /> instance referencing this action map.
    /// </summary>
    public PlayerRunner1Actions @PlayerRunner1 => new PlayerRunner1Actions(this);

    // PlayerRunner2
    private readonly InputActionMap m_PlayerRunner2;
    private List<IPlayerRunner2Actions> m_PlayerRunner2ActionsCallbackInterfaces = new List<IPlayerRunner2Actions>();
    private readonly InputAction m_PlayerRunner2_MoveToLane1;
    private readonly InputAction m_PlayerRunner2_MoveToLane2;
    private readonly InputAction m_PlayerRunner2_MoveToLane3;
    private readonly InputAction m_PlayerRunner2_MoveToLane4;
    /// <summary>
    /// Provides access to input actions defined in input action map "PlayerRunner2".
    /// </summary>
    public struct PlayerRunner2Actions
    {
        private @MiniGame1_InputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PlayerRunner2Actions(@MiniGame1_InputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "PlayerRunner2/MoveToLane1".
        /// </summary>
        public InputAction @MoveToLane1 => m_Wrapper.m_PlayerRunner2_MoveToLane1;
        /// <summary>
        /// Provides access to the underlying input action "PlayerRunner2/MoveToLane2".
        /// </summary>
        public InputAction @MoveToLane2 => m_Wrapper.m_PlayerRunner2_MoveToLane2;
        /// <summary>
        /// Provides access to the underlying input action "PlayerRunner2/MoveToLane3".
        /// </summary>
        public InputAction @MoveToLane3 => m_Wrapper.m_PlayerRunner2_MoveToLane3;
        /// <summary>
        /// Provides access to the underlying input action "PlayerRunner2/MoveToLane4".
        /// </summary>
        public InputAction @MoveToLane4 => m_Wrapper.m_PlayerRunner2_MoveToLane4;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_PlayerRunner2; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PlayerRunner2Actions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PlayerRunner2Actions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PlayerRunner2Actions" />
        public void AddCallbacks(IPlayerRunner2Actions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerRunner2ActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerRunner2ActionsCallbackInterfaces.Add(instance);
            @MoveToLane1.started += instance.OnMoveToLane1;
            @MoveToLane1.performed += instance.OnMoveToLane1;
            @MoveToLane1.canceled += instance.OnMoveToLane1;
            @MoveToLane2.started += instance.OnMoveToLane2;
            @MoveToLane2.performed += instance.OnMoveToLane2;
            @MoveToLane2.canceled += instance.OnMoveToLane2;
            @MoveToLane3.started += instance.OnMoveToLane3;
            @MoveToLane3.performed += instance.OnMoveToLane3;
            @MoveToLane3.canceled += instance.OnMoveToLane3;
            @MoveToLane4.started += instance.OnMoveToLane4;
            @MoveToLane4.performed += instance.OnMoveToLane4;
            @MoveToLane4.canceled += instance.OnMoveToLane4;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PlayerRunner2Actions" />
        private void UnregisterCallbacks(IPlayerRunner2Actions instance)
        {
            @MoveToLane1.started -= instance.OnMoveToLane1;
            @MoveToLane1.performed -= instance.OnMoveToLane1;
            @MoveToLane1.canceled -= instance.OnMoveToLane1;
            @MoveToLane2.started -= instance.OnMoveToLane2;
            @MoveToLane2.performed -= instance.OnMoveToLane2;
            @MoveToLane2.canceled -= instance.OnMoveToLane2;
            @MoveToLane3.started -= instance.OnMoveToLane3;
            @MoveToLane3.performed -= instance.OnMoveToLane3;
            @MoveToLane3.canceled -= instance.OnMoveToLane3;
            @MoveToLane4.started -= instance.OnMoveToLane4;
            @MoveToLane4.performed -= instance.OnMoveToLane4;
            @MoveToLane4.canceled -= instance.OnMoveToLane4;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PlayerRunner2Actions.UnregisterCallbacks(IPlayerRunner2Actions)" />.
        /// </summary>
        /// <seealso cref="PlayerRunner2Actions.UnregisterCallbacks(IPlayerRunner2Actions)" />
        public void RemoveCallbacks(IPlayerRunner2Actions instance)
        {
            if (m_Wrapper.m_PlayerRunner2ActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PlayerRunner2Actions.AddCallbacks(IPlayerRunner2Actions)" />
        /// <seealso cref="PlayerRunner2Actions.RemoveCallbacks(IPlayerRunner2Actions)" />
        /// <seealso cref="PlayerRunner2Actions.UnregisterCallbacks(IPlayerRunner2Actions)" />
        public void SetCallbacks(IPlayerRunner2Actions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerRunner2ActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerRunner2ActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PlayerRunner2Actions" /> instance referencing this action map.
    /// </summary>
    public PlayerRunner2Actions @PlayerRunner2 => new PlayerRunner2Actions(this);

    // PlayerRunner3
    private readonly InputActionMap m_PlayerRunner3;
    private List<IPlayerRunner3Actions> m_PlayerRunner3ActionsCallbackInterfaces = new List<IPlayerRunner3Actions>();
    private readonly InputAction m_PlayerRunner3_MoveToLane1;
    private readonly InputAction m_PlayerRunner3_MoveToLane2;
    private readonly InputAction m_PlayerRunner3_MoveToLane3;
    private readonly InputAction m_PlayerRunner3_MoveToLane4;
    /// <summary>
    /// Provides access to input actions defined in input action map "PlayerRunner3".
    /// </summary>
    public struct PlayerRunner3Actions
    {
        private @MiniGame1_InputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PlayerRunner3Actions(@MiniGame1_InputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "PlayerRunner3/MoveToLane1".
        /// </summary>
        public InputAction @MoveToLane1 => m_Wrapper.m_PlayerRunner3_MoveToLane1;
        /// <summary>
        /// Provides access to the underlying input action "PlayerRunner3/MoveToLane2".
        /// </summary>
        public InputAction @MoveToLane2 => m_Wrapper.m_PlayerRunner3_MoveToLane2;
        /// <summary>
        /// Provides access to the underlying input action "PlayerRunner3/MoveToLane3".
        /// </summary>
        public InputAction @MoveToLane3 => m_Wrapper.m_PlayerRunner3_MoveToLane3;
        /// <summary>
        /// Provides access to the underlying input action "PlayerRunner3/MoveToLane4".
        /// </summary>
        public InputAction @MoveToLane4 => m_Wrapper.m_PlayerRunner3_MoveToLane4;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_PlayerRunner3; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PlayerRunner3Actions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PlayerRunner3Actions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PlayerRunner3Actions" />
        public void AddCallbacks(IPlayerRunner3Actions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerRunner3ActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerRunner3ActionsCallbackInterfaces.Add(instance);
            @MoveToLane1.started += instance.OnMoveToLane1;
            @MoveToLane1.performed += instance.OnMoveToLane1;
            @MoveToLane1.canceled += instance.OnMoveToLane1;
            @MoveToLane2.started += instance.OnMoveToLane2;
            @MoveToLane2.performed += instance.OnMoveToLane2;
            @MoveToLane2.canceled += instance.OnMoveToLane2;
            @MoveToLane3.started += instance.OnMoveToLane3;
            @MoveToLane3.performed += instance.OnMoveToLane3;
            @MoveToLane3.canceled += instance.OnMoveToLane3;
            @MoveToLane4.started += instance.OnMoveToLane4;
            @MoveToLane4.performed += instance.OnMoveToLane4;
            @MoveToLane4.canceled += instance.OnMoveToLane4;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PlayerRunner3Actions" />
        private void UnregisterCallbacks(IPlayerRunner3Actions instance)
        {
            @MoveToLane1.started -= instance.OnMoveToLane1;
            @MoveToLane1.performed -= instance.OnMoveToLane1;
            @MoveToLane1.canceled -= instance.OnMoveToLane1;
            @MoveToLane2.started -= instance.OnMoveToLane2;
            @MoveToLane2.performed -= instance.OnMoveToLane2;
            @MoveToLane2.canceled -= instance.OnMoveToLane2;
            @MoveToLane3.started -= instance.OnMoveToLane3;
            @MoveToLane3.performed -= instance.OnMoveToLane3;
            @MoveToLane3.canceled -= instance.OnMoveToLane3;
            @MoveToLane4.started -= instance.OnMoveToLane4;
            @MoveToLane4.performed -= instance.OnMoveToLane4;
            @MoveToLane4.canceled -= instance.OnMoveToLane4;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PlayerRunner3Actions.UnregisterCallbacks(IPlayerRunner3Actions)" />.
        /// </summary>
        /// <seealso cref="PlayerRunner3Actions.UnregisterCallbacks(IPlayerRunner3Actions)" />
        public void RemoveCallbacks(IPlayerRunner3Actions instance)
        {
            if (m_Wrapper.m_PlayerRunner3ActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PlayerRunner3Actions.AddCallbacks(IPlayerRunner3Actions)" />
        /// <seealso cref="PlayerRunner3Actions.RemoveCallbacks(IPlayerRunner3Actions)" />
        /// <seealso cref="PlayerRunner3Actions.UnregisterCallbacks(IPlayerRunner3Actions)" />
        public void SetCallbacks(IPlayerRunner3Actions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerRunner3ActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerRunner3ActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PlayerRunner3Actions" /> instance referencing this action map.
    /// </summary>
    public PlayerRunner3Actions @PlayerRunner3 => new PlayerRunner3Actions(this);
    private int m_KeyboardSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "PlayerRunner" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PlayerRunnerActions.AddCallbacks(IPlayerRunnerActions)" />
    /// <seealso cref="PlayerRunnerActions.RemoveCallbacks(IPlayerRunnerActions)" />
    public interface IPlayerRunnerActions
    {
        /// <summary>
        /// Method invoked when associated input action "MoveToLane1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMoveToLane1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MoveToLane2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMoveToLane2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MoveToLane3" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMoveToLane3(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MoveToLane4" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMoveToLane4(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "PlayerRunner1" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PlayerRunner1Actions.AddCallbacks(IPlayerRunner1Actions)" />
    /// <seealso cref="PlayerRunner1Actions.RemoveCallbacks(IPlayerRunner1Actions)" />
    public interface IPlayerRunner1Actions
    {
        /// <summary>
        /// Method invoked when associated input action "MoveToLane1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMoveToLane1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MoveToLane2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMoveToLane2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MoveToLane3" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMoveToLane3(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MoveToLane4" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMoveToLane4(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "PlayerRunner2" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PlayerRunner2Actions.AddCallbacks(IPlayerRunner2Actions)" />
    /// <seealso cref="PlayerRunner2Actions.RemoveCallbacks(IPlayerRunner2Actions)" />
    public interface IPlayerRunner2Actions
    {
        /// <summary>
        /// Method invoked when associated input action "MoveToLane1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMoveToLane1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MoveToLane2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMoveToLane2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MoveToLane3" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMoveToLane3(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MoveToLane4" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMoveToLane4(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "PlayerRunner3" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PlayerRunner3Actions.AddCallbacks(IPlayerRunner3Actions)" />
    /// <seealso cref="PlayerRunner3Actions.RemoveCallbacks(IPlayerRunner3Actions)" />
    public interface IPlayerRunner3Actions
    {
        /// <summary>
        /// Method invoked when associated input action "MoveToLane1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMoveToLane1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MoveToLane2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMoveToLane2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MoveToLane3" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMoveToLane3(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MoveToLane4" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMoveToLane4(InputAction.CallbackContext context);
    }
}
